// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9uyDl6qO5yEZV6aT6co5GU7YN0zvzBc',
    appId: '1:478789221336:web:c0aa8ad7f54f265b7610ad',
    messagingSenderId: '478789221336',
    projectId: 'instazeal-5193c',
    authDomain: 'instazeal-5193c.firebaseapp.com',
    storageBucket: 'instazeal-5193c.appspot.com',
    measurementId: 'G-5HT48R3SFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPzylm381EzVjcZj8fJqr6BH4Ky-3RAU',
    appId: '1:478789221336:android:c75a65774130fc697610ad',
    messagingSenderId: '478789221336',
    projectId: 'instazeal-5193c',
    storageBucket: 'instazeal-5193c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxoD4Ds5Jmi9YYBNWwZhinOtmpXgeijg',
    appId: '1:478789221336:ios:436445c5573657d47610ad',
    messagingSenderId: '478789221336',
    projectId: 'instazeal-5193c',
    storageBucket: 'instazeal-5193c.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );
}
